config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  
  resources :agents, only: [:index, :new, :create, :show]
  resources :properties
  get 'search', to: 'properties#search', as: :search_properties

  get 'contact', to: 'static_pages#contact', as: :contact
  get 'about', to: 'static_pages#about', as: :about

  resources :users, only: [:show]

  namespace :admin do
    resources :properties, except: [:show]
    resources :users, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
   has_many :properties
   has_one_attached :photo
 
   validates :name, presence: true
   validates :contact_information, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :agent  # This line establishes the relationship

  has_many_attached :images
  # Add other property-related validations and associations as needed
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  before_action :require_admin
  before_action :set_property, only: [:edit, :update, :destroy]

  def index
    @properties = Property.all
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      redirect_to admin_properties_path, notice: 'Property created successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @property.update(property_params)
      redirect_to admin_properties_path, notice: 'Property updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @property.destroy
    redirect_to admin_properties_path, notice: 'Property deleted successfully.'
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name, :price, :location, :description, :agent_id, images: [])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User deleted successfully.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :admin)
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def index
    @agents = Agent.all
  end

  def new
    @agent = Agent.new
  end

  def show
    puts "Params ID: #{params[:id]}"
    @agent = Agent.find(params[:id])
  end

  def create
    @agent = Agent.new(agent_params)
    if @agent.save
      redirect_to agents_path, notice: 'Agent was successfully created.'
    else
      render :new
    end
  end

  private

  def agent_params
    params.require(:agent).permit(:name, :contact_information, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def require_admin
    unless current_user.admin?
      redirect_to root_path, alert: 'You are not authorized to access this page.'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]

  def index
    @properties = Property.all
  end

  def show
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      redirect_to properties_path, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  def edit
    # This action is now defined, and it uses the set_property callback to find the record
  end

  def search
    @properties = Property.all
    @properties = @properties.where("location LIKE ?", "%#{params[:search]}%") if params[:search].present?
    @properties = @properties.where("price >= ?", params[:min_price]) if params[:min_price].present?
    @properties = @properties.where("price <= ?", params[:max_price]) if params[:max_price].present?
    @properties = @properties.page(params[:page]).per(9)
  end

  def update
    if @property.update(property_params)
      redirect_to properties_path, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @property.destroy
    redirect_to properties_path, notice: 'Property was successfully deleted.'
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name, :location, :price, :description, images: [])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/properties_helper.rb
module Admin::PropertiesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/properties/edit.html.erb
<h1>Edit Property</h1>

<%= form_with model: @property, url: admin_properties_path, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: 'form-control' %>
  </div>

  <%= form.submit 'Edit Property', class: 'btn btn-success' %>
<% end %>

app/views/admin/properties/index.html.erb
<h1>Manage Properties</h1>

<%= link_to 'Add New Property', new_admin_property_path, class: 'btn btn-success' %>

<table class="table table-striped mt-4">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Location</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td>$<%= property.price %></td>
        <td><%= property.location %></td>
        <td>
          <%= link_to 'Edit', edit_admin_property_path(property), class: 'btn btn-primary' %>
          <%= link_to 'Delete', admin_property_path(property), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/properties/new.html.erb
<h1>Add New Property</h1>

<%= form_with model: @property, url: admin_properties_path, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: 'form-control' %>
  </div>

  <%= form.submit 'Create Property', class: 'btn btn-success' %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user, url: admin_user_path(@user), local: true do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control', readonly: true %>
  </div>

  <div class="form-group">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <%= form.submit 'Update User', class: 'btn btn-success' %>
<% end %>

app/views/admin/users/index.html.erb
<h1>Manage Users</h1>

<table class="table table-striped mt-4">
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin? ? 'Yes' : 'No' %></td>
        <td>
          <%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-primary' %>
          <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/agents/index.html.erb
<section class="container mt-5">
  <h1>Agents</h1>
  <div class="row mt-4">
    <% @agents.each do |agent| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <%= image_tag agent.photo.variant(resize_to_limit: [300, 300]).processed, class: 'card-img-top' if agent.photo.attached? %>
          <div class="card-body">
            <h5 class="card-title"><%= agent.name %></h5>
            <p class="card-text"><%= agent.contact_information %></p>
            <%= link_to 'View Listings', agent_path(agent), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/agents/new.html.erb
<section class="container mt-5">
  <h1>Create Agent</h1>
  
  <%= form_with model: @agent, local: true do |form| %>
    <div class="row">
      <div class="col-md-6">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-6">
        <%= form.label :contact_information %>
        <%= form.text_field :contact_information, class: "form-control" %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-12">
        <%= form.label :photo %>
        <%= form.file_field :photo, class: "form-control" %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-12">
        <%= form.submit 'Create Agent', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</section>

app/views/agents/show.html.erb
<section class="container mt-5">
  <h1><%= @agent.name %></h1>
  
  <% if @agent.photo.attached? %>
    <%= image_tag @agent.photo.variant(resize_to_limit: [300, 300]).processed, class: 'img-fluid' %>
  <% end %>

  <h3>Contact Information</h3>
  <p><%= @agent.contact_information %></p>

  <h3>Listings</h3>
  <div class="row">
    <% @agent.properties.each do |property| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <% if property.images.attached? %>
            <%= image_tag property.images.first.variant(resize_to_limit: [300, 300]).processed, class: 'card-img-top' %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= property.name %></h5>
            <p class="card-text">$<%= property.price %> - <%= property.location %></p>
            <%= link_to 'View Details', property_path(property), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/home/index.html.erb
<section class="container text-center mt-5">
  <h1>Welcome to Our Real Estate Agency</h1>
  <p>Your dream property is just a click away!</p>

      <% if user_signed_in? %>
      <%= link_to 'Profile', user_path(current_user), class: 'btn btn-primary' %>
      <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success' %>
    <% end %>


  <div class="mt-4">
    <%= link_to 'Agent Directory', agents_path, class: 'btn btn-primary btn-lg mx-2' %>
    <%= link_to 'Property Listings', properties_path, class: 'btn btn-secondary btn-lg mx-2' %>
    <%= link_to 'Contact Us', contact_path, class: 'btn btn-info btn-lg mx-2' %>
    <%= link_to 'About Us', about_path, class: 'btn btn-success btn-lg mx-2' %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealEstateApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/index.html.erb
<section class="container mt-5">
  <h1>Manage Properties</h1>
  <%= link_to 'Add New Property', new_property_path, class: 'btn btn-primary mb-3' %>

  <div class="row">
    <% @properties.each do |property| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <%= image_tag(property.images.first, class: 'card-img-top') if property.images.any? %>
          <div class="card-body">
            <h5 class="card-title"><%= property.name %></h5>
            <p class="card-text">$<%= property.price %> - <%= property.location %></p>
            <%= link_to 'Edit', edit_property_path(property), class: 'btn btn-secondary' %>
            <%= link_to 'Delete', property, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/properties/new.html.erb
<section class="container mt-5">
  <h1>Edit Property</h1>

  <%= form_with(model: @property, local: true, html: { multipart: true }) do |form| %>
    <div class="row">
      <div class="col-md-6">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="col-md-6">
        <%= form.label :location %>
        <%= form.text_field :location, class: 'form-control' %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-6">
        <%= form.label :price %>
        <%= form.number_field :price, class: 'form-control' %>
      </div>

      <div class="col-md-6">
        <%= form.label :images %>
        <%= form.file_field :images, class: 'form-control', multiple: true %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-12">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-md-12">
        <%= form.submit 'Update Property', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</section>

app/views/properties/search.html.erb
<section class="container mt-5">
  <h1>Advanced Property Search</h1>

  <%= form_with url: search_properties_path, method: :get, local: true do |form| %>
    <div class="row">
      <div class="col-md-6">
        <%= form.label :search, "Location" %>
        <%= form.text_field :search, class: "form-control", placeholder: "Enter location" %>
      </div>

      <div class="col-md-3">
        <%= form.label :min_price, "Minimum Price" %>
        <%= form.number_field :min_price, class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= form.label :max_price, "Maximum Price" %>
        <%= form.number_field :max_price, class: "form-control" %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-4">
        <%= form.submit 'Search', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <div class="row mt-5">
    <% @properties.each do |property| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <%= image_tag(property.images.first, class: 'card-img-top') if property.images.any? %>
          <div class="card-body">
            <h5 class="card-title"><%= property.name %></h5>
            <p class="card-text">$<%= property.price %> - <%= property.location %></p>
            <%= link_to 'View Details', property_path(property), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= paginate @properties %>
</section>

app/views/properties/show.html.erb
<section class="container mt-5">
  <div class="row">
    <div class="col-md-8">
      <h1><%= @property.name %></h1>
      <p class="lead">$<%= @property.price %> - <%= @property.location %></p>

      <div id="property-images" class="mb-4">
        <% @property.images.each do |image| %>
          <%= image_tag image.variant(resize: "800x400"), class: "img-fluid mb-2" %>
        <% end %>
      </div>

      <h3>Description</h3>
      <p><%= @property.description %></p>

      <h3>Amenities and Features</h3>
      <ul>
        <!-- Add specific amenities and features here -->
      </ul>
    </div>

    <div class="col-md-4">
      <h3>Location</h3>
      <div id="map" style="width: 100%; height: 300px;"></div>
    </div>
  </div>
</section>

app/views/static_pages/about.html.erb
<section class="container mt-5">
  <h1>About Us</h1>
  <p>Welcome to our real estate agency! We are dedicated to helping you find your dream property.</p>
  
  <h3>Our Mission</h3>
  <p>To provide exceptional service and expert guidance to our clients.</p>

  <h3>Follow Us</h3>
  <div>
    <a href="https://facebook.com" target="_blank">Facebook</a> |
    <a href="https://twitter.com" target="_blank">Twitter</a> |
    <a href="https://instagram.com" target="_blank">Instagram</a>
  </div>
</section>

app/views/static_pages/contact.html.erb
<section class="container mt-5">
  <h1>Contact Us</h1>
  
  <%= form_with url: contact_path, local: true do |form| %>
    <div class="row">
      <div class="col-md-6">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-6">
        <%= form.label :email %>
        <%= form.email_field :email, class: "form-control" %>
      </div>
    </div>
    
    <div class="row mt-3">
      <div class="col-md-12">
        <%= form.label :message %>
        <%= form.text_area :message, class: "form-control", rows: 5 %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-12">
        <%= form.submit 'Send Message', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</section>

app/views/users/show.html.erb
<h1><%= @user.email %>'s Profile</h1>

<p>Email: <%= @user.email %></p>

<%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %>